#!/bin/bash
#apiKey="<apiKey>"
#apiSecret="<apiSecret>"
#telegramToken="<message_@BotFather_on_telegram>"
#telegramId="<message_@MyIDbot_on_telegram>"

cryptos=("AAVE" "ADA" "ALGO" "ANKR" "ATOM" "FIL" "GRT" "HBAR" "HNT" "IOTA" "MANA" "MATIC" "MKR" "OMG" "ONE" "QTUM" "UNI" "VET" "VTHO" "WAVES")

otherFlags="--live 1 --sellatresistance 1 --stats 1 --disablebullonly 1"

restartTimer=60

silenceNotifications=0

exchange="binance"
apiUrl="https://api.binance.us"
currency="USD"

wireguardSwitching=0

# these are generally ok to be left as is, change only if neccesary
dir="$(pwd)"
usrnme="$(logname)"
